HELP_1 = """<b><u>ADMIN COMMANDS :</b></u>

JUST ADD <b>C</b> IN THE STARTING OF THE COMMANDS TO USE THEM FOR CHANNEL.


/pauSe : PAUSE THE CURRENT PLAYING STREAM.

/reSume : RESUME THE PAUSED STREAM.

/Skip : SKIP THE CURRENT PLAYING STREAM AND START STREAMING THE NEXT TRACK IN QUEUE.

/end OR /Stop : CLEARS THE QUEUE AND END THE CURRENT PLAYING STREAM.

/player : GET A INTERACTIVE PLAYER PANEL.

/queue : SHOWS THE QUEUED TRACKS LIST.
"""

HELP_2 = """
<b><u>AUTH USERS :</b></u>

AUTH USERS CAN USE ADMIN RIGHTS IN THE BOT WITHOUT ADMIN RIGHTS IN THE CHAT.

/auth [USERNAME/USER_ID] : ADD A USER TO AUTH LIST OF THE BOT.
/unauth [USERNAME/USER_ID] : REMOVE A AUTH USERS FROM THE AUTH USERS LIST.
/authuSerS : SHOWS THE LIST OF AUTH USERS OF THE GROUP.
"""

HELP_3 = """
<u><b>BROADCAST FEATURE</b></u> [ONLY FOR SUDOERS] :

/broadcaSt [MESSAGE OR REPLY TO A MESSAGE] : BROADCAST A MESSAGE TO SERVED CHATS OF THE BOT.

<u>BROADCASTING MODES :</u>
<b>-pin</b> : PINS YOUR BROADCASTED MESSAGES IN SERVED CHATS.
<b>-pinloud</b> : PINS YOUR BROADCASTED MESSAGE IN SERVED CHATS AND SEND NOTIFICATION TO THE MEMBERS.
<b>-uSer</b> : BROADCASTS THE MESSAGE TO THE USERS WHO HAVE STARTED YOUR BOT.
<b>-aSSiStant</b> : BROADCAST YOUR MESSAGE FROM THE ASSITANT ACCOUNT OF THE BOT.
<b>-nobot</b> : FORCES THE BOT TO NOT BROADCAST THE MESSAGE..

<b>EXAMPLE:</b> <code>/broadcaSt -uSer -aSSiStant -pin TESTING BROADCAST</code>
"""

HELP_4 = """<u><b>CHAT BLACKLIST FEATURE :</b></u> [ONLY FOR SUDOERS]

RESTRICT SHIT CHATS TO USE OUR PRECIOUS BOT.

/blackliStchat [CHAT ID] : BLACKLIST A CHAT FROM USING THE BOT.
/whiteliStchat [CHAT ID] : WHITELIST THE BLACKLISTED CHAT.
/blackliStedchat : SHOWS THE LIST OF BLACKLISTED CHATS.
"""

HELP_5 = """
<u><b>BLOCK USERS:</b></u> [ONLY FOR SUDOERS]

STARTS IGNORING THE BLACKLISTED USER, SO THAT HE CAN'T USE BOT COMMANDS.

/block [USERNAME OR REPLY TO A USER] : BLOCK THE USER FROM OUR BOT.
/unblock [USERNAME OR REPLY TO A USER] : UNBLOCKS THE BLOCKED USER.
/blockeduSerS : SHOWS THE LIST OF BLOCKED USERS.
"""

HELP_6 = """
<u><b>CHANNEL PLAY COMMANDS:</b></u>

YOU CAN STREAM AUDIO/VIDEO IN CHANNEL.

/cplay : STARTS STREAMING THE REQUESTED AUDIO TRACK ON CHANNEL'S VIDEOCHAT.
/cvplay : STARTS STREAMING THE REQUESTED VIDEO TRACK ON CHANNEL'S VIDEOCHAT.
/cplayforce or /cvplayforce : STOPS THE ONGOING STREAM AND STARTS STREAMING THE REQUESTED TRACK.

/channelplay [CHAT USERNAME OR ID] OR [DISABLE] : CONNECT CHANNEL TO A GROUP AND STARTS STREAMING TRACKS BY THE HELP OF COMMANDS SENT IN GROUP.
"""

HELP_7 = """
<u><b>GLOBAL BAN FEATURE</b></u> [ONLY FOR SUDOERS] :

/gban [USERNAME OR REPLY TO A USER] : GLOBALLY BANS THE CHUTIYA FROM ALL THE SERVED CHATS AND BLACKLIST HIM FROM USING THE BOT.
/ungban [USERNAME OR REPLY TO A USER] : GLOBALLY UNBANS THE GLOBALLY BANNED USER.
/gbanneduSerS : SHOWS THE LIST OF GLOBALLY BANNED USERS.
"""

HELP_8 = """
<b><u>LOOP STREAM :</b></u>

<b>STARTS STREAMING THE ONGOING STREAM IN LOOP</b>

/loop [enable/diSable] : ENABLES/DISABLES LOOP FOR THE ONGOING STREAM
/loop [1, 2, 3, ...] : ENABLES THE LOOP FOR THE GIVEN VALUE.
"""

HELP_9 = """
<u><b>MAINTENANCE MODE</b></u> [ONLY FOR SUDOERS] :

/logS : GET LOGS OF THE BOT.

/logger [ENABLE/DISABLE] : BOT WILL START LOGGING THE ACTIVITIES HAPPEN ON BOT.

/maintenance [ENABLE/DISABLE] : ENABLE OR DISABLE THE MAINTENANCE MODE OF YOUR BOT.
"""

HELP_10 = """
<b><u>PING & STATS :</b></u>

/Start : STARTS THE MUSIC BOT.
/help : GET HELP MENU WITH EXPLANATION OF COMMANDS.

/ping : SHOWS THE PING AND SYSTEM STATS OF THE BOT.

/StatS : SHOWS THE OVERALL STATS OF THE BOT.
"""

HELP_11 = """
<u><b>PLAY COMMANDS :</b></u>

<b>v :</b> STANDS FOR VIDEO PLAY.
<b>force :</b> STANDS FOR FORCE PLAY.

/play OR /vplay : STARTS STREAMING THE REQUESTED TRACK ON VIDEOCHAT.

/playforce OR /vplayforce : STOPS THE ONGOING STREAM AND STARTS STREAMING THE REQUESTED TRACK.
"""

HELP_12 = """
<b><u>SHUFFLE ǪUEUE :</b></u>

/Shuffle : SHUFFLE'S THE ǪUEUE.
/queue : SHOWS THE SHUFFLED ǪUEUE.
"""

HELP_13 = """
<b><u>SEEK STREAM :</b></u>

/Seek [DURATION IN SECONDS] : SEEK THE STREAM TO THE GIVEN DURATION.
/Seekback [DURATION IN SECONDS] : BACKWARD SEEK THE STREAM TO THE THE GIVEN DURATION.
"""

HELP_14 = """
<b><u>SONG DOWNLOAD</b></u>

/Song [SONG NAME/YT URL] : DOWNLOAD ANY TRACK FROM YOUTUBE IN MP3 OR MP4 FORMATS.
"""

HELP_15 = """
<b><u>SPEED COMMANDS :</b></u>

YOU CAN CONTROL THE PLAYBACK SPEED OF THE ONGOING STREAM. [ADMINS ONLY]

/Speed or /playback : FOR ADJUSTING THE AUDIO PLAYBACK SPEED IN GROUP.
/cSpeed or /cplayback : FOR ADJUSTING THE AUDIO PLAYBACK SPEED IN CHANNEL.
"""
